// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Junior Paz"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "description": "Accounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Accounts",
                "parameters": [
                    {
                        "description": "createInputDto request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.createInputDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.createOutputDto"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/account.createOutputDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    }
                }
            }
        },
        "/accounts/{id}": {
            "get": {
                "description": "Get All By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Get All By Id",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "account_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.getAllByIdOutputDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/credit": {
            "post": {
                "description": "Credit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Credit",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "account_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "creditInputDto request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.creditInputDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.creditOutputDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    }
                }
            }
        },
        "/books": {
            "get": {
                "description": "Get by Instrument",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Books"
                ],
                "summary": "Get by Instrument",
                "parameters": [
                    {
                        "type": "string",
                        "description": "instrument",
                        "name": "instrument",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/book.getByInstrumentOutputDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    }
                }
            }
        },
        "/orders": {
            "post": {
                "description": "Orders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Orders",
                "parameters": [
                    {
                        "description": "placeInputDto request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.placeInputDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/order.placeOutputDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    }
                }
            }
        },
        "/orders/{id}/cancel": {
            "post": {
                "description": "Orders Cancel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Orders Cancel",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "order_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.cancelOutputDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.Errors"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.createInputDto": {
            "type": "object",
            "required": [
                "account_name"
            ],
            "properties": {
                "account_name": {
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "account.createOutputDto": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "status": {
                    "type": "string",
                    "example": "created"
                }
            }
        },
        "account.creditBalanceOutputDto": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer",
                    "example": 1000
                },
                "reserved": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "account.creditInputDto": {
            "type": "object",
            "required": [
                "amount",
                "asset"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 1000
                },
                "asset": {
                    "type": "string",
                    "example": "USD"
                }
            }
        },
        "account.creditOutputDto": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "balances": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/account.creditBalanceOutputDto"
                    }
                }
            }
        },
        "account.getAllByIdBalanceOutputDto": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer",
                    "example": 1000
                },
                "reserved": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "account.getAllByIdOutputDto": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "balances": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/account.getAllByIdBalanceOutputDto"
                    }
                }
            }
        },
        "book.getByInstrumentLevelOutputDto": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer",
                    "example": 50000
                },
                "qty": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "book.getByInstrumentOutputDto": {
            "type": "object",
            "properties": {
                "asks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/book.getByInstrumentLevelOutputDto"
                    }
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/book.getByInstrumentLevelOutputDto"
                    }
                },
                "instrument": {
                    "type": "string",
                    "example": "BTC/USDT"
                }
            }
        },
        "order.cancelOutputDto": {
            "type": "object",
            "properties": {
                "order": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "type": "string",
                    "example": "canceled"
                }
            }
        },
        "order.placeInputDto": {
            "type": "object",
            "required": [
                "account_id",
                "instrument",
                "price",
                "qty",
                "side"
            ],
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "instrument": {
                    "type": "string",
                    "example": "BTC-USD"
                },
                "price": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 50000
                },
                "qty": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "side": {
                    "type": "string",
                    "enum": [
                        "buy",
                        "sell"
                    ],
                    "example": "buy"
                }
            }
        },
        "order.placeOutputDto": {
            "type": "object",
            "properties": {
                "order": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "report": {
                    "$ref": "#/definitions/order.placeTradeReportOutputDto"
                }
            }
        },
        "order.placeTradeOutputDto": {
            "type": "object",
            "required": [
                "price",
                "qty"
            ],
            "properties": {
                "buyer_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "maker_order_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "price": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 50000
                },
                "qty": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "seller_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "taker_order_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "order.placeTradeReportOutputDto": {
            "type": "object",
            "properties": {
                "trades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/order.placeTradeOutputDto"
                    }
                }
            }
        },
        "shared.Errors": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "The 'name' field is required"
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "Invalid parameter"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Clob API",
	Description:      "Clob API without Authentication",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
